### ISSUE TITLE
license for code?

### ISSUE THREAD

**Issue by takahashir986** [LTTM/Scan-to-BIM#4]
Hi, thank you very much for sharing your great work.

I would like to know if the code share the same license with the dataset.
> Our dataset is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

If not, could you tell me which license is applied to the code?

Thank you.

**Comment by elenacamuffo** [comment]
Hello, thank you very much for your appreciation.
Yes, the code shares the same license with the dataset.
