### ISSUE TITLE
schedule for pretrained models

### ISSUE THREAD

**Issue by takahashir986** [LTTM/Scan-to-BIM#5]
Hi, I have one more question.

Is it decided when the pretrained models are to be released?
>Pretrained models --> coming soon!

Thank you!

**Comment by elenacamuffo** [comment]
Hello,
They will be released no later than September 2024, but hopefully sooner.

**Comment by elenacamuffo** [comment]
Pretrained models have been uploaded [here](https://drive.google.com/drive/folders/1hSW5MRQY10q9-EUXBZU4G-agZNrp_CAG?usp=drive_link).
