### ISSUE TITLE
Inference on a raw Point Cloud

### ISSUE THREAD

**Issue by Rizulv** [LTTM/Scan-to-BIM#6]
Hello,
I wanted to know how can i use the pretrained model BIM NET ++ to perform inference on my raw pcd? 
and do i need to have a cleaned pcd or will the model automatically will do that.
and also how will the output look ? like will i get a bim file , pcd file with labelled info? 
Please help me clear these things.
rizulv.jpr@gmail.com

**Comment by elenacamuffo** [comment]
Hello Rizulv,

To use the pretrained BIM-Net++ model you can use the validation routine in the `train_pcs.py` file and specify the link of your model in the `--pretrain` argument. 
That will provide you with the output predictions (numbers) and you can replace the values in your original point clouds (.txt in our case) for each point to get the visual output and/or reconstruct the model geometry.
This works if you want to use our HePIC dataset. But as I understand from your message, you have your own dataset. In this case, you'd better start with one of our data loaders and modify it according to the format of your data.
In our model point clouds have been cleaned beforehand. But if you need other information about this, please e-mail my co-authors from the Dept. of Civil Engineering (reported in the paper) as they know more about the acquisition process.

I hope it will help. 

Elena

**Comment by Rizulv** [comment]
Hello elena,
I will surely try the method you suggested and meanwhile can you please provide me with the email id's of your co-authors? 
Thank you

**Comment by elenacamuffo** [comment]
You can find them in the pdf [here](https://ieeexplore.ieee.org/abstract/document/10222064)

**Comment by Rizulv** [comment]
Sorry Elena but there is not gmail id mentioned on the github.
If you can please email me the id's on my gmail account that would be really helpful.
Apart from this I made inference pipeline and the results i got included the semantic segmentation of my points.
But that was a little chaotic.
email - rizulv.jpr@gmail.com
